# Generated by Django 5.2.7 on 2025-12-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='For teachers: whether admin has approved this teacher'),
        ),
    ]
