# Generated by Django 5.2.8 on 2025-11-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="PDF, DOC, DOCX, or other document file",
                null=True,
                upload_to="lesson_documents/",
            ),
        ),
    ]
