# Generated by Django 5.2.7 on 2025-12-23 07:54

from django.db import migrations
import re


def normalize_video_url(url):
    """
    Normalize video URL to embed format for YouTube, or return as-is for other URLs.
    """
    if not url or not isinstance(url, str):
        return url
    
    url = url.strip()
    if not url:
        return url
    
    # If already an embed URL, return as is
    if 'youtube.com/embed/' in url:
        return url
    
    # Pattern for youtube.com/watch?v=VIDEO_ID
    watch_pattern = r'(?:https?://)?(?:www\.)?youtube\.com/watch\?v=([a-zA-Z0-9_-]+)'
    match = re.search(watch_pattern, url)
    if match:
        video_id = match.group(1)
        return f'https://www.youtube.com/embed/{video_id}'
    
    # Pattern for youtu.be/VIDEO_ID
    short_pattern = r'(?:https?://)?(?:www\.)?youtu\.be/([a-zA-Z0-9_-]+)'
    match = re.search(short_pattern, url)
    if match:
        video_id = match.group(1)
        return f'https://www.youtube.com/embed/{video_id}'
    
    # For other URLs, return as is
    return url


def normalize_video_urls_forward(apps, schema_editor):
    """
    Normalize all existing video_urls in Lesson model.
    Converts YouTube URLs to embed format.
    """
    Lesson = apps.get_model('courses', 'Lesson')
    
    # Get all lessons with video_url
    lessons = Lesson.objects.exclude(video_url__isnull=True).exclude(video_url='')
    
    updated_count = 0
    for lesson in lessons:
        if lesson.video_url:
            normalized_url = normalize_video_url(lesson.video_url)
            # Only update if URL changed
            if normalized_url != lesson.video_url:
                lesson.video_url = normalized_url
                lesson.save(update_fields=['video_url'])
                updated_count += 1
    
    print(f"Normalized {updated_count} video URLs")


def normalize_video_urls_reverse(apps, schema_editor):
    """
    Reverse migration - cannot reverse URL normalization.
    This is a one-way operation.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_document_file'),
    ]

    operations = [
        migrations.RunPython(normalize_video_urls_forward, normalize_video_urls_reverse),
    ]
