# Generated by Django 5.2.7 on 2025-12-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_normalize_video_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReplacementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_video_url', models.URLField()),
                ('new_video_url', models.URLField()),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text="Reason for replacement (e.g., 'video_unavailable')", max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_replacements', to='courses.lesson')),
            ],
            options={
                'db_table': 'video_replacement_logs',
                'ordering': ['-replaced_at'],
            },
        ),
    ]
