# Generated by Django 5.2.7 on 2025-12-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_typing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'typing_indicators',
                'indexes': [models.Index(fields=['receiver', 'is_typing'], name='typing_indi_receive_19efab_idx')],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
