# Generated by Django 5.2.7 on 2025-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('quiz_created', 'Quiz Created'), ('quiz_updated', 'Quiz Updated'), ('assignment_created', 'Assignment Created'), ('assignment_updated', 'Assignment Updated'), ('lesson_created', 'Lesson Created'), ('lesson_updated', 'Lesson Updated'), ('section_created', 'Section Created'), ('section_updated', 'Section Updated'), ('grade_released', 'Grade Released'), ('student_submission', 'Student Submission'), ('question_posted', 'Question Posted')], default='quiz_created', max_length=50),
        ),
    ]
