# Generated by Django 5.2.7 on 2025-12-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
