# Generated by Django 5.2.7 on 2025-12-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_add_start_time_end_time_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='correct_answers',
            field=models.IntegerField(default=0, help_text='Number of correct answers'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total number of questions in quiz'),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='score',
            field=models.FloatField(default=0, help_text='Score as percentage (0-100)'),
        ),
    ]
