# Generated by Django 5.2.8 on 2025-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="progress_percent",
            field=models.PositiveIntegerField(
                default=0, help_text="Progress percentage (0-100)"
            ),
        ),
    ]
