# Generated by Django 5.2.7 on 2025-12-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_lesson_document_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='announcements.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcement_read_statuses',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='announcemen_created_f85040_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['course', '-created_at'], name='announcemen_course__dd5413_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementreadstatus',
            index=models.Index(fields=['student', 'is_read'], name='announcemen_student_8006cd_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementreadstatus',
            index=models.Index(fields=['announcement', 'is_read'], name='announcemen_announc_0f99a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementreadstatus',
            unique_together={('announcement', 'student')},
        ),
    ]
